// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from 'eslint-plugin-storybook';

import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Generated by Serwist from app/sw.ts (next.config.ts → swDest) — compiled output, not source
    'public/sw.js',
    'public/sw.js.map',
    'public/swe-worker-*.js',
    'public/swe-worker-*.js.map',
    // Python scraper (incl. its virtualenv, which bundles third-party JS/TS)
    'scraper/**',
    '**/venv/**',
    '**/.venv/**',
    // Tool output
    'storybook-static/**',
    'coverage/**',
  ]),
  ...storybook.configs['flat/recommended'],
]);

export default eslintConfig;
